// AUTO-GENERATED by scripts/version_gen.py - do not edit.
// Regenerated on every build from the VERSION file + git state.
#pragma once

namespace AstrOsConstants
{
    constexpr const char *Version = "1.1.0-dev.64";
    constexpr const char *GitSha = "4c53168";
}
